[package]
name = "CoonBridge"
version = "1.0.0"
description = "An app for managing Coon Gallery backups and AI description generation."
authors = ["Botpa"]
edition = "2021"

[lib]
name = "coon_bridge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-single-instance = "2.0.0"
tauri-plugin-autostart = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = "0.3.33"
# Server
tokio = "1.53.1"
tokio-tungstenite = "0.30.0"
local-ip-address = "0.6.13"
# Database
rusqlite = { version = "0.31", features = ["bundled"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-cli = "2"

